### ISSUE TITLE
Camera view on iOS doesn't work

### ISSUE THREAD

**Issue by moehrlef** [PiotrFLEURY/camcode#7]
When open the CamCodeScanner() in Safari/Chomre/FireFox on my IPhone XR (14.4.2) i just get an black screen. But i get the red camera icon and the green dot which indicate that the camera is activated.

On Android and Desktop it works fine in all browsers. Andy hints?

Thanks in forward.

**Comment by PiotrFLEURY** [comment]
Hi @moehrlef

Thanks for your feedback.
This plugin uses the standard web API `navigator.mediaDevices.getUserMedia(constraints)`. As described in the documentation [here](https://developer.mozilla.org/fr/docs/Web/API/MediaDevices/getUserMedia), the Desktop and Android web browsers are compatible but only Safari on IOS is supposed to work.
Unfortunately, many developers are facing the same issue. In fact, it does not always work.

Some threads are giving potential fixes : 
[https://developer.apple.com/forums/thread/92713](https://developer.apple.com/forums/thread/92713)
[https://stackoverflow.com/questions/45692526/ios-11-getusermedia-not-working](https://stackoverflow.com/questions/45692526/ios-11-getusermedia-not-working)

I will to look at this point and try to provide a fix as quickly as possible.

Regards

**Comment by moehrlef** [comment]
Thanks a lot for your fast feedback!

**Comment by PiotrFLEURY** [comment]
Hi @moehrlef 

I just fixed the black screen problem on IOS in 2.0.1 version.
I've tested it on, Desktop Chrome, Android Chrome and IOS Chrome + Safari. All works well.

Just be sure to **cleanup your web cache** in order to force your browser to load the latest version of the code.

Demo URL has also been updated [https://camcode-59c70.web.app/#/](https://camcode-59c70.web.app/#/)

Feel free to send any feedback

Regards
Piotr FLEURY
